In [2]:
import pandas as pd

customers =pd.read_csv(r"C:\Users\dell\Documents\E-Commerce-Customer-Behaviour-Revenue-Analytics\data\raw\practice_customers.csv")
orders  = pd.read_csv(r"C:\Users\dell\Documents\E-Commerce-Customer-Behaviour-Revenue-Analytics\data\raw\practice_Orders.csv")
order_items = pd.read_csv(r"C:\Users\dell\Documents\E-Commerce-Customer-Behaviour-Revenue-Analytics\data\raw\practice_OrderItems.csv")
payments =pd.read_csv(r"C:\Users\dell\Documents\E-Commerce-Customer-Behaviour-Revenue-Analytics\data\raw\practice_Payments.csv")
products = pd.read_csv(r"C:\Users\dell\Documents\E-Commerce-Customer-Behaviour-Revenue-Analytics\data\raw\practice_Products.csv")

In [4]:
print(customers.shape)

(4025, 4)

In [5]:
customers.head()

  customer_id  customer_zip_code_prefix customer_city customer_state
0  CUST100000                     55699     df_city_2             DF
1  CUST100001                     50992     mg_city_3             MG
2  CUST100002                     16520     pe_city_1             PE
3  CUST100003                     20697     ba_city_2             BA
4  CUST100004                     63576     sp_city_3             SP

In [6]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4025 entries, 0 to 4024
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               4025 non-null   object
 1   customer_zip_code_prefix  4025 non-null   int64
 2   customer_city             4025 non-null   object
 3   customer_state            3965 non-null   object
dtypes: int64(1), object(3)
memory usage: 125.9+ KB

In [8]:
print(orders.shape)

(10691, 4)

In [9]:
orders.head()

,order_id,customer_id,order_purchase_timestamp,order_approved_at
0,ORD0000001,CUST100000,2024-03-24 09:00:00,2024-03-25 16:07:29.205198109
1,ORD0000002,CUST100000,2024-06-13 07:00:00,2024-06-13 22:16:21.627711193
2,ORD0000003,CUST100001,2023-05-26 23:00:00,2023-05-27 04:10:08.449491314
3,ORD0000004,CUST100001,2023-11-21 23:00:00,2023-11-22 01:28:11.359202872
4,ORD0000005,CUST100002,2023-03-02 15:00:00,2023-03-02 23:38:54.330060236

In [10]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10691 entries, 0 to 10690
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  10691 non-null  object
 1   customer_id               10691 non-null  object
 2   order_purchase_timestamp  10691 non-null  object
 3   order_approved_at         10477 non-null  object
dtypes: object(4)
memory usage: 334.2+ KB

In [11]:
print(order_items.shape)

(14622, 5)

In [12]:
order_items.head()

     order_id product_id seller_id   price  shipping_charges
0  ORD0000001   PROD2089  SELL0171  171.53             10.86
1  ORD0000001   PROD2665  SELL0062   71.94             19.13
2  ORD0000002   PROD2256  SELL0079  106.83             12.34
3  ORD0000002   PROD2445  SELL0252   23.11             16.52
4  ORD0000003   PROD2883  SELL0152  263.62             15.23

In [13]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14622 entries, 0 to 14621
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          14622 non-null  object
 1   product_id        14622 non-null  object
 2   seller_id         14622 non-null  object
 3   price             14622 non-null  float64
 4   shipping_charges  14622 non-null  float64
dtypes: float64(2), object(3)
memory usage: 571.3+ KB

In [14]:
print(payments.shape)

(10691, 5)

In [15]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,ORD0000001,1,voucher,1,271.45
1,ORD0000002,1,credit_card,1,157.09
2,ORD0000003,1,credit_card,6,279.99
3,ORD0000004,1,voucher,1,85.35
4,ORD0000005,1,credit_card,2,228.66

In [16]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10691 entries, 0 to 10690
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              10691 non-null  object
 1   payment_sequential    10691 non-null  int64
 2   payment_type          10691 non-null  object
 3   payment_installments  10691 non-null  int64
 4   payment_value         10691 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 417.7+ KB

In [17]:
print(products.shape)

(900, 6)

In [18]:
products.head()

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,PROD2000,furniture_decor,5707.0,7,55,91
1,PROD2001,watches_gifts,2444.0,74,61,7
2,PROD2002,computers_accessories,3624.0,74,69,40
3,PROD2003,pet_shop,2930.0,13,37,51
4,PROD2004,garden_tools,3721.0,88,27,5

In [19]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             900 non-null    object
 1   product_category_name  880 non-null    object
 2   product_weight_g       885 non-null    float64
 3   product_length_cm      900 non-null    int64
 4   product_height_cm      900 non-null    int64
 5   product_width_cm       900 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 42.3+ KB

In [21]:
print(customers.duplicated().sum())
print(orders.duplicated().sum())
print(order_items.duplicated().sum())
print(payments.duplicated().sum())
print(products.duplicated().sum())

25
0
0
0
0

In [22]:
customers[customers.duplicated(keep=False)].sort_values("customer_id")

     customer_id  customer_zip_code_prefix customer_city customer_state
102   CUST100102                     23529     sp_city_1             SP
4010  CUST100102                     23529     sp_city_1             SP
200   CUST100200                     58211     df_city_2             DF
4000  CUST100200                     58211     df_city_2             DF
420   CUST100420                     56829     sc_city_3             SC
4016  CUST100420                     56829     sc_city_3             SC
557   CUST100557                     77492     mg_city_1             MG
4023  CUST100557                     77492     mg_city_1             MG
4002  CUST100610                     85814     rs_city_1             RS
610   CUST100610                     85814     rs_city_1             RS
813   CUST100813                     96598     pr_city_3             PR
4007  CUST100813                     96598     pr_city_3             PR
4009  CUST100870                     67936     df_city_1             DF
870   CUST100870                     67936     df_city_1             DF
4021  CUST101050                     22939     sc_city_1             SC
1050  CUST101050                     22939     sc_city_1             SC
4001  CUST101078                     93369     pr_city_1             PR
1078  CUST101078                     93369     pr_city_1             PR
1098  CUST101098                     95080     pe_city_2             PE
4012  CUST101098                     95080     pe_city_2             PE
4004  CUST101169                     53111     sp_city_3             SP
1169  CUST101169                     53111     sp_city_3             SP
4020  CUST101239                     34027     sp_city_2             SP
1239  CUST101239                     34027     sp_city_2             SP
4008  CUST101268                     30155     mg_city_3             MG
1268  CUST101268                     30155     mg_city_3             MG
4019  CUST101359                     51159     sp_city_3             SP
1359  CUST101359                     51159     sp_city_3             SP
4018  CUST101398                     61490     rs_city_3             RS
1398  CUST101398                     61490     rs_city_3             RS
1419  CUST101419                     24160     ma_city_2             MA
4014  CUST101419                     24160     ma_city_2             MA
1814  CUST101814                     84896     es_city_2             ES
4013  CUST101814                     84896     es_city_2             ES
2159  CUST102159                     96029     sp_city_3             SP
4003  CUST102159                     96029     sp_city_3             SP
2290  CUST102290                     60675     ma_city_1             MA
4015  CUST102290                     60675     ma_city_1             MA
4005  CUST102448                     56016     pr_city_2             PR
2448  CUST102448                     56016     pr_city_2             PR
4017  CUST102473                     42811     rs_city_1             RS
2473  CUST102473                     42811     rs_city_1             RS
4006  CUST102938                     63826     sp_city_3             SP
2938  CUST102938                     63826     sp_city_3             SP
4024  CUST103195                     56278     rj_city_2             RJ
3195  CUST103195                     56278     rj_city_2             RJ
3256  CUST103256                     14403     sp_city_1             SP
4011  CUST103256                     14403     sp_city_1             SP
4022  CUST103500                     87115     mg_city_1             MG
3500  CUST103500                     87115     mg_city_1             MG

In [25]:
customers_clean = customers.drop_duplicates().copy()
print(customers_clean.shape)

(4000, 4)

In [26]:
customers_clean["customer_state"] = customers_clean["customer_state"].fillna("unknown")

In [27]:
customers_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 3999
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               4000 non-null   object
 1   customer_zip_code_prefix  4000 non-null   int64
 2   customer_city             4000 non-null   object
 3   customer_state            4000 non-null   object
dtypes: int64(1), object(3)
memory usage: 156.2+ KB

In [29]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])
orders["order_approved_at"] = pd.to_datetime(orders["order_approved_at"])

In [30]:
orders["approval_delay"] = orders["order_approved_at"] - orders["order_purchase_timestamp"]

In [31]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10691 entries, 0 to 10690
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  10691 non-null  object
 1   customer_id               10691 non-null  object
 2   order_purchase_timestamp  10691 non-null  datetime64[ns]
 3   order_approved_at         10477 non-null  datetime64[ns]
 4   approval_delay            10477 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), object(2), timedelta64[ns](1)
memory usage: 417.7+ KB

In [32]:
orders["approval_delay"].head()

0   1 days 07:07:29.205198109
1   0 days 15:16:21.627711193
2   0 days 05:10:08.449491314
3   0 days 02:28:11.359202872
4   0 days 08:38:54.330060236
Name: approval_delay, dtype: timedelta64[ns]

In [33]:
avg_delay = orders["approval_delay"].mean()
print(avg_delay)

0 days 05:01:27.742815837

In [34]:
orders["order_approved_at"] = orders["order_approved_at"].fillna(
    orders["order_purchase_timestamp"] + avg_delay
)

In [36]:
orders["order_approved_at"].isnull().sum()

np.int64(0)

In [37]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10691 entries, 0 to 10690
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  10691 non-null  object
 1   customer_id               10691 non-null  object
 2   order_purchase_timestamp  10691 non-null  datetime64[ns]
 3   order_approved_at         10691 non-null  datetime64[ns]
 4   approval_delay            10477 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), object(2), timedelta64[ns](1)
memory usage: 417.7+ KB

In [38]:
orders["approval_delay"] = orders["order_approved_at"] - orders["order_purchase_timestamp"]
orders["approval_delay"].isnull().sum()

np.int64(0)

In [39]:
products_clean = products.copy()
products_clean["product_category_name"] = products_clean["product_category_name"].fillna("unknown")

In [40]:
median_weight = products_clean["product_weight_g"].median()
products_clean["product_weight_g"] = products_clean["product_weight_g"].fillna(median_weight)

In [41]:
products_clean.isnull().sum()

product_id               0
product_category_name    0
product_weight_g         0
product_length_cm        0
product_height_cm        0
product_width_cm         0
dtype: int64

In [49]:
master = orders.merge(customers_clean, on="customer_id", how="left")
print(master.shape)
master.head()

(10691, 8)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,approval_delay,customer_zip_code_prefix,customer_city,customer_state
0,ORD0000001,CUST100000,2024-03-24 09:00:00,2024-03-25 16:07:29.205198109,1 days 07:07:29.205198109,55699,df_city_2,DF
1,ORD0000002,CUST100000,2024-06-13 07:00:00,2024-06-13 22:16:21.627711193,0 days 15:16:21.627711193,55699,df_city_2,DF
2,ORD0000003,CUST100001,2023-05-26 23:00:00,2023-05-27 04:10:08.449491314,0 days 05:10:08.449491314,50992,mg_city_3,MG
3,ORD0000004,CUST100001,2023-11-21 23:00:00,2023-11-22 01:28:11.359202872,0 days 02:28:11.359202872,50992,mg_city_3,MG
4,ORD0000005,CUST100002,2023-03-02 15:00:00,2023-03-02 23:38:54.330060236,0 days 08:38:54.330060236,16520,pe_city_1,PE

In [50]:
master = master.merge(order_items, on="order_id", how="left")
print(master.shape)

(14622, 12)

In [51]:
master = master.merge(products_clean, on="product_id", how="left")
print(master.shape)

(14622, 17)

In [52]:
master = master.merge(payments, on="order_id", how="left")
print(master.shape)

(14622, 21)

In [54]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14622 entries, 0 to 14621
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  14622 non-null  object
 1   customer_id               14622 non-null  object
 2   order_purchase_timestamp  14622 non-null  datetime64[ns]
 3   order_approved_at         14622 non-null  datetime64[ns]
 4   approval_delay            14622 non-null  timedelta64[ns]
 5   customer_zip_code_prefix  14622 non-null  int64
 6   customer_city             14622 non-null  object
 7   customer_state            14622 non-null  object
 8   product_id                14622 non-null  object
 9   seller_id                 14622 non-null  object
 10  price                     14622 non-null  float64
 11  shipping_charges          14622 non-null  float64
 12  product_category_name     14622 non-null  object
 13  product_weight_g          14622 non-null  float64
 14  product_length_cm         14622 non-null  int64
 15  product_height_cm         14622 non-null  int64
 16  product_width_cm          14622 non-null  int64
 17  payment_sequential        14622 non-null  int64
 18  payment_type              14622 non-null  object
 19  payment_installments      14622 non-null  int64
 20  payment_value             14622 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(6), object(8), timedelta64[ns](1)
memory usage: 2.3+ MB

In [56]:
master.to_csv(r"C:\Users\dell\Documents\E-Commerce-Customer-Behaviour-Revenue-Analytics\data\processed\master_cleaned.csv", index=False)